### ISSUE TITLE
Ability to install in partition among Linux

### ISSUE THREAD

**Issue by Ygarr** [project-trident/trident-build#20]
Please add ability to install on HDD or SSD where already are located linux partitions
![2019-01-23-000301_1006x405_scrot](https://user-images.githubusercontent.com/14309871/51568390-46a0f680-1ea2-11e9-9d25-99d03a71e1b7.png)

**Comment by q5sys** [comment]
Due to the way ZFS works and how the bootloader needs to work.  My gut instinct is that this would not work.  But I'll tag it in case someone wants to do the work.

I dont know of any linux bootloader that can load a specific ZFS snapshot.  On the flip side, I dont believe the FreeBSD bootloader can boot a linux partition.

**Comment by beanpole135** [comment]
I also want to point out that FreeBSD does not support logical partitions, only real/primary partitions when using an MBR partitioning scheme. (Although GPT partitioning is much better supported).

I think you should open an issue with either the TrueOS or FreeBSD projects to see if bootloader issues can be addressed.

https://github.com/trueos/trueos
https://bugs.freebsd.org
