### ISSUE TITLE
Automount and autounmount are not work in the new release

### ISSUE THREAD

**Issue by ZoltanHegedus** [project-trident/trident-build#29]
In the new Trident TOS 1907 the automount and autounmount services are not work. The connected USB devices, the insider DVD writer and second SSD are invisible in my machine.

**Comment by RodMyers** [comment]
rc-status | grep auto
 automountd                                                        [  started  ]
 autounmountd                                          [  started 12:43:16 (0) ]
 automount                                                         [  started  ]


they are working on 1907.

It's a devd(?) regression

**Comment by beanpole135** [comment]
This will be fixed in the 19.07-U1 update. Turns out TrueOS has removed all the filesystem automount integrations from their latest changes. I had to go into the archives and find/copy those routines into Trident itself for the next round of builds.

You can easily re-enable it on your system right now if you copy that one file from the commit below, and insert one line into /etc/auto_master to enable the rule.

https://github.com/project-trident/trident-core/commit/92c4c26ddd33e715540e3038f240371928c3a444

**Comment by ZoltanHegedus** [comment]
Thank's your answers!

Have a nice day!
