### ISSUE TITLE
Can I plug the pkg repo into my TrueOS Desctop?

### ISSUE THREAD

**Issue by sailorsamoor** [project-trident/trident-build#9]
Hello. I have TrueOS Desktop in which pkg repo does not upgrade. While I wait for Project Trident migration script (or until I deside to upgrade myself)  can I plug its repo?

Best regards,
Vladimir.

**Comment by beanpole135** [comment]
I would recommend installing Project Trident into a new boot environment on your system instead of trying to do a live-upgrade.
This will ensure that everything gets migrated appropriately, but your user data will still be left completely intact (just remember to create the same user that you had before).

**Comment by sailorsamoor** [comment]
Thanks, Ken.
